### ISSUE TITLE
dataset's file missing

### ISSUE THREAD

**Issue by wuw2135** [AbnerVictor/OOD-GAN-inversion#4]
Hi, I discovered that the dataset folder was empty. Could you provide the complete file? I am unable to locate 'stylegan2-ffhq-config-f_avg_latent.pt' on the internet. Thank you.

**Comment by AbnerVictor** [comment]
Sorry for the missing file, currently I am not able to access my data for this project at the moment due to technical issues. For your information, the average latent could also be find inside stylegan2-ffhq checkpoints (including both the weights and average latent of stylegan2 model) on the internet.

I will upload necessary files later on, thank you for asking
